// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: api/proto/vector/vector.proto

package vector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_vector_vector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vector_vector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_vector_vector_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*Chunk               `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_vector_vector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vector_vector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_vector_vector_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,4,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	StartPos      int32                  `protobuf:"varint,5,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"`
	EndPos        int32                  `protobuf:"varint,6,opt,name=end_pos,json=endPos,proto3" json:"end_pos,omitempty"`
	WordCount     int32                  `protobuf:"varint,7,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	Score         float32                `protobuf:"fixed32,8,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_api_proto_vector_vector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vector_vector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_api_proto_vector_vector_proto_rawDescGZIP(), []int{2}
}

func (x *Chunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chunk) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Chunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Chunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *Chunk) GetStartPos() int32 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *Chunk) GetEndPos() int32 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

func (x *Chunk) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *Chunk) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_api_proto_vector_vector_proto protoreflect.FileDescriptor

const file_api_proto_vector_vector_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/vector/vector.proto\x12\x06vector\";\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"7\n" +
	"\x0eSearchResponse\x12%\n" +
	"\x06chunks\x18\x01 \x03(\v2\r.vector.ChunkR\x06chunks\"\xde\x01\n" +
	"\x05Chunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vchunk_index\x18\x04 \x01(\x05R\n" +
	"chunkIndex\x12\x1b\n" +
	"\tstart_pos\x18\x05 \x01(\x05R\bstartPos\x12\x17\n" +
	"\aend_pos\x18\x06 \x01(\x05R\x06endPos\x12\x1d\n" +
	"\n" +
	"word_count\x18\a \x01(\x05R\twordCount\x12\x14\n" +
	"\x05score\x18\b \x01(\x02R\x05score2H\n" +
	"\rVectorService\x127\n" +
	"\x06Search\x12\x15.vector.SearchRequest\x1a\x16.vector.SearchResponseB@Z>github.com/chongs12/enterprise-knowledge-base/api/proto/vectorb\x06proto3"

var (
	file_api_proto_vector_vector_proto_rawDescOnce sync.Once
	file_api_proto_vector_vector_proto_rawDescData []byte
)

func file_api_proto_vector_vector_proto_rawDescGZIP() []byte {
	file_api_proto_vector_vector_proto_rawDescOnce.Do(func() {
		file_api_proto_vector_vector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_vector_vector_proto_rawDesc), len(file_api_proto_vector_vector_proto_rawDesc)))
	})
	return file_api_proto_vector_vector_proto_rawDescData
}

var file_api_proto_vector_vector_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_vector_vector_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: vector.SearchRequest
	(*SearchResponse)(nil), // 1: vector.SearchResponse
	(*Chunk)(nil),          // 2: vector.Chunk
}
var file_api_proto_vector_vector_proto_depIdxs = []int32{
	2, // 0: vector.SearchResponse.chunks:type_name -> vector.Chunk
	0, // 1: vector.VectorService.Search:input_type -> vector.SearchRequest
	1, // 2: vector.VectorService.Search:output_type -> vector.SearchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_vector_vector_proto_init() }
func file_api_proto_vector_vector_proto_init() {
	if File_api_proto_vector_vector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_vector_vector_proto_rawDesc), len(file_api_proto_vector_vector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_vector_vector_proto_goTypes,
		DependencyIndexes: file_api_proto_vector_vector_proto_depIdxs,
		MessageInfos:      file_api_proto_vector_vector_proto_msgTypes,
	}.Build()
	File_api_proto_vector_vector_proto = out.File
	file_api_proto_vector_vector_proto_goTypes = nil
	file_api_proto_vector_vector_proto_depIdxs = nil
}
